# Generated by Django 4.2.13 on 2026-05-18 20:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(max_length=10)),
                ('from_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('to_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('gross_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('fee_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('spread_percent', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fee_percent', models.DecimalField(decimal_places=4, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('reference_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('debit_tx', models.UUIDField(blank=True, null=True)),
                ('credit_tx', models.UUIDField(blank=True, null=True)),
                ('fee_tx', models.UUIDField(blank=True, null=True)),
                ('exchange_rate_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='wallet.wallet')),
            ],
            options={
                'db_table': 'conversion_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Merchant',
                'db_table': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('inr_from_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('usdt_converted', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=15)),
                ('inr_from_conversion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=20)),
                ('reference_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('wallet_tx', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='transactions.merchant')),
                ('related_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='transactions.conversionhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wallet.wallet')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_flags', to='wallet.wallettransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='wallet.wallet')),
            ],
            options={
                'db_table': 'risk_flags',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='risk_flags_user_id_57ccd0_idx'), models.Index(fields=['severity', 'is_reviewed'], name='risk_flags_severit_bfd4a6_idx')],
            },
        ),
    ]
