# Generated by Django 4.2.13 on 2026-05-18 19:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(max_length=10)),
                ('from_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('to_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('gross_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('fee_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('spread_percent', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fee_percent', models.DecimalField(decimal_places=4, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('reference_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('debit_tx', models.UUIDField(blank=True, null=True)),
                ('credit_tx', models.UUIDField(blank=True, null=True)),
                ('fee_tx', models.UUIDField(blank=True, null=True)),
                ('exchange_rate_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='wallet.wallet')),
            ],
            options={
                'db_table': 'conversion_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=255)),
                ('merchant_id', models.CharField(default='MERCHANT_SIM', max_length=100)),
                ('merchant_category', models.CharField(default='General', max_length=100)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('inr_from_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('usdt_converted', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=15)),
                ('inr_from_conversion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=20)),
                ('reference_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('wallet_tx', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='transactions.conversionhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wallet.wallet')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
