# Generated by Django 4.2.13 on 2026-05-18 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '__first__'),
        ('blockchain', '__first__'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='blockchain_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='blockchain.blockchaintransaction'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='merchants.merchantqrcode'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='settlement_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='blockchain.settlementevent'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Payment Created'), ('QR_GENERATED', 'QR Code Generated'), ('PENDING_SIGNATURE', 'Pending Wallet Signature'), ('SIGNATURE_RECEIVED', 'Signature Received'), ('BLOCKCHAIN_SUBMITTED', 'Submitted to Blockchain'), ('MEMPOOL_PENDING', 'Pending in Mempool'), ('CONFIRMING', 'Confirming'), ('CONFIRMED', 'Confirmed'), ('SETTLEMENT_PROCESSING', 'Processing Settlement'), ('SETTLED', 'Settled'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('EXPIRED', 'Expired'), ('FRAUD_REVIEW', 'Under Fraud Review')], db_index=True, default='CREATED', max_length=30),
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
    ]
