# Generated by Django 4.2.13 on 2026-05-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_paymenttransaction_blockchain_tx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Payment Created'), ('SUBMITTED', 'Submitted to Blockchain'), ('CONFIRMED', 'Confirmed & Settled'), ('FAILED', 'Failed')], db_index=True, default='CREATED', max_length=30),
        ),
    ]
