# Generated by Django 4.2.13 on 2026-05-18 20:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'db_table': 'journal_entries',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('USER', 'User Wallet'), ('MERCHANT', 'Merchant Wallet'), ('TREASURY_EXTERNAL', 'External Banking System'), ('TREASURY_RESERVE_INR', 'INR Reserve Treasury'), ('TREASURY_RESERVE_USDT', 'USDT Reserve Treasury'), ('TREASURY_FEES', 'Fee Collection Treasury')], default='USER', max_length=30)),
                ('inr_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('usdt_balance', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USDT', 'Tether USD')], max_length=10)),
                ('category', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('CONVERSION', 'Conversion'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('FEE', 'Fee'), ('REVERSAL', 'Reversal')], default='DEPOSIT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('balance_before', models.DecimalField(decimal_places=8, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=8, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='COMPLETED', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.journalentry')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related', to='wallet.wallettransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'currency', '-created_at'], name='wallet_tran_wallet__992b63_idx'), models.Index(fields=['status', '-created_at'], name='wallet_tran_status_aa67b2_idx'), models.Index(fields=['reference_id'], name='wallet_tran_referen_1f3089_idx')],
            },
        ),
    ]
