# Generated by Django 4.2.13 on 2026-05-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='web3_address',
            field=models.CharField(blank=True, help_text='Linked external EVM wallet address', max_length=42, null=True, unique=True),
        ),
    ]
