# Generated by Django 4.2.13 on 2026-05-18 21:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_web3_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='label',
            field=models.CharField(blank=True, help_text='Display name for treasury/merchant wallets', max_length=255),
        ),
        migrations.AddField(
            model_name='wallet',
            name='usdc_balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=24),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('USER', 'User Wallet'), ('MERCHANT', 'Merchant Wallet'), ('TREASURY_EXTERNAL', 'External Banking System'), ('TREASURY_EXTERNAL_UPI', 'UPI On-Ramp Treasury'), ('TREASURY_USDC_RESERVE', 'USDC Reserve Treasury'), ('TREASURY_RESERVE_INR', 'INR Reserve Treasury'), ('TREASURY_RESERVE_USDT', 'USDT Reserve Treasury'), ('TREASURY_SETTLEMENT', 'Merchant Settlement Pool'), ('TREASURY_FEES', 'Fee Collection Treasury'), ('TREASURY_BLOCKCHAIN_GAS', 'Gas Reserve Treasury'), ('TREASURY_RISK_BUFFER', 'Risk Buffer Treasury')], default='USER', max_length=30),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USDT', 'Tether USD'), ('USDC', 'USD Coin')], max_length=10),
        ),
    ]
