# Generated by Django 4.2.13 on 2026-05-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_label_wallet_usdc_balance_alter_wallet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Display name for treasury/merchant wallets', max_length=255),
        ),
    ]
