# Generated by Django 4.2.13 on 2026-05-18 21:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('from_address', models.CharField(db_index=True, max_length=42)),
                ('to_address', models.CharField(db_index=True, max_length=42)),
                ('token_contract', models.CharField(max_length=42)),
                ('token_symbol', models.CharField(default='USDC', max_length=20)),
                ('amount_raw', models.CharField(max_length=78)),
                ('amount_human', models.DecimalField(decimal_places=8, max_digits=24)),
                ('chain_id', models.IntegerField(default=80002)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('required_confirmations', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted to Mempool'), ('MEMPOOL_PENDING', 'Pending in Mempool'), ('CONFIRMING', 'Collecting Confirmations'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed / Reverted'), ('DROPPED', 'Dropped from Mempool'), ('REORGED', 'Block Reorg Detected')], db_index=True, default='SUBMITTED', max_length=20)),
                ('submitted_via_provider', models.CharField(blank=True, max_length=50)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('gas_price_gwei', models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True)),
                ('payment_intent_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('qr_code_nonce', models.CharField(blank=True, db_index=True, max_length=100)),
                ('decoded_log', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blockchain_transactions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_id', models.UUIDField(blank=True, null=True)),
                ('usdc_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('fee_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('net_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('journal_entry_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('SETTLED', 'Settled'), ('FAILED', 'Failed'), ('DISPUTED', 'Disputed')], default='PROCESSING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blockchain_tx', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='blockchain.blockchaintransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settlement_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['status', '-submitted_at'], name='blockchain__status_27680e_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['from_address', '-submitted_at'], name='blockchain__from_ad_b0396c_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['to_address', '-submitted_at'], name='blockchain__to_addr_3bc192_idx'),
        ),
    ]
