# Generated by Django 4.2.13 on 2026-05-18 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('WALLET_BALANCE', 'Wallet Balance Integrity'), ('JOURNAL_BALANCE', 'Journal Entry Net-Zero'), ('TREASURY_INTEGRITY', 'Treasury Total Integrity'), ('BLOCKCHAIN_SETTLEMENT', 'Blockchain Settlement Verification'), ('ORPHAN_TRANSACTIONS', 'Orphan Transaction Detection')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('PASS', 'Pass — No Discrepancies'), ('FAIL', 'Fail — Discrepancies Found'), ('ERROR', 'Error — Reconciliation Failed')], db_index=True, max_length=10)),
                ('records_checked', models.IntegerField(default=0)),
                ('discrepancy_count', models.IntegerField(default=0)),
                ('discrepancies', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reconciliation_reports',
                'ordering': ['-run_at'],
                'indexes': [models.Index(fields=['report_type', 'status', '-run_at'], name='reconciliat_report__cb016a_idx')],
            },
        ),
    ]
