# Generated by Django 4.2.13 on 2026-05-18 19:30

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_pair', models.CharField(db_index=True, max_length=20)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bid', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('spread', models.DecimalField(decimal_places=4, default=Decimal('0.5'), max_digits=10)),
                ('source', models.CharField(default='CoinGecko', max_length=50)),
                ('is_live', models.BooleanField(default=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exchange_rates',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['currency_pair', '-fetched_at'], name='exchange_ra_currenc_e66b3f_idx')],
            },
        ),
    ]
