# Generated by Django 4.2.13 on 2026-05-18 21:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0003_wallet_label_wallet_usdc_balance_alter_wallet_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('business_type', models.CharField(default='General', max_length=100)),
                ('category', models.CharField(default='General', max_length=100)),
                ('wallet_address', models.CharField(help_text='Public EVM address where USDC payments arrive on-chain', max_length=42, unique=True)),
                ('fee_structure', models.JSONField(blank=True, default=dict, help_text='e.g. {"settlement_fee_pct": 0.5, "min_fee_usdc": 0.01}')),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 risk score')),
                ('kyb_verified', models.BooleanField(default=False)),
                ('kyb_verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_KYB', 'Pending KYB Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], db_index=True, default='PENDING_KYB', max_length=20)),
                ('total_settlements_usdc', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('total_payment_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_wallet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_account', to='wallet.wallet')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_wallet_address', models.CharField(max_length=42)),
                ('amount_usdc', models.DecimalField(decimal_places=8, max_digits=24)),
                ('currency', models.CharField(default='USDC', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('nonce', models.CharField(db_index=True, max_length=64, unique=True)),
                ('signed_payload', models.TextField()),
                ('hmac_signature', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active — Awaiting Payment'), ('SCANNED', 'Scanned by User'), ('PENDING_SIGNATURE', 'Awaiting MetaMask Signature'), ('SIGNATURE_RECEIVED', 'Signature Received'), ('BLOCKCHAIN_SUBMITTED', 'Blockchain Transaction Submitted'), ('COMPLETED', 'Payment Completed'), ('EXPIRED', 'Expired'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=30)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, db_index=True, max_length=66)),
                ('scan_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_for_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_qr_codes', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_codes', to='merchants.merchant')),
            ],
            options={
                'db_table': 'merchant_qr_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'status', '-created_at'], name='merchant_qr_merchan_84aee4_idx'), models.Index(fields=['expires_at', 'status'], name='merchant_qr_expires_3a230a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['wallet_address'], name='merchants_wallet__7f4284_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['status', '-created_at'], name='merchants_status_36c324_idx'),
        ),
    ]
