# Generated by Django 4.2.13 on 2026-05-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantqrcode',
            name='is_consumed',
            field=models.BooleanField(default=False, help_text='Permanently lock the QR after successful settlement.'),
        ),
    ]
