"""
Merchants App — Models
========================
Merchant: Onboarded business entity with settlement account
MerchantQRCode: Time-limited, HMAC-signed payment QR with full lifecycle
"""
import uuid
import hmac
import hashlib
import json
from decimal import Decimal
from django.db import models
from django.conf import settings
from django.utils import timezone


class MerchantStatus(models.TextChoices):
    PENDING_KYB = "PENDING_KYB", "Pending KYB Verification"
    ACTIVE = "ACTIVE", "Active"
    SUSPENDED = "SUSPENDED", "Suspended"
    TERMINATED = "TERMINATED", "Terminated"


class Merchant(models.Model):
    """
    Represents an onboarded merchant entity.
    Has its own internal settlement wallet and an on-chain EVM address
    where USDC payments are received directly via MetaMask.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="merchant_profile",
        null=True, blank=True,
    )
    name = models.CharField(max_length=255, unique=True, db_index=True)
    business_type = models.CharField(max_length=100, default="General")
    category = models.CharField(max_length=100, default="General")

    # The on-chain EVM address where this merchant receives USDC payments
    # Verified on registration — NEVER stored as private key, only public address
    wallet_address = models.CharField(
        max_length=42, unique=True,
        help_text="Public EVM address where USDC payments arrive on-chain"
    )

    # Internal NexusPay settlement account (separate from blockchain)
    internal_wallet = models.OneToOneField(
        "wallet.Wallet",
        on_delete=models.PROTECT,
        related_name="merchant_account",
        null=True, blank=True,
    )

    # Fee structure (stored as JSON for flexibility)
    fee_structure = models.JSONField(
        default=dict,
        blank=True,
        help_text='e.g. {"settlement_fee_pct": 0.5, "min_fee_usdc": 0.01}'
    )

    # Risk
    risk_score = models.IntegerField(default=0, help_text="0-100 risk score")

    # KYB
    kyb_verified = models.BooleanField(default=False)
    kyb_verified_at = models.DateTimeField(null=True, blank=True)

    status = models.CharField(
        max_length=20,
        choices=MerchantStatus.choices,
        default=MerchantStatus.PENDING_KYB,
        db_index=True,
    )

    # Analytics cache
    total_settlements_usdc = models.DecimalField(max_digits=24, decimal_places=8, default=Decimal("0"))
    total_payment_count = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "merchants"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["wallet_address"]),
            models.Index(fields=["status", "-created_at"]),
        ]

    def __str__(self):
        return f"{self.name} [{self.status}]"

    def get_fee_pct(self) -> Decimal:
        return Decimal(str(self.fee_structure.get("settlement_fee_pct", 0.5)))


class QRCodeStatus(models.TextChoices):
    ACTIVE = "ACTIVE", "Active — Awaiting Payment"
    SCANNED = "SCANNED", "Scanned by User"
    PENDING_SIGNATURE = "PENDING_SIGNATURE", "Awaiting MetaMask Signature"
    SIGNATURE_RECEIVED = "SIGNATURE_RECEIVED", "Signature Received"
    BLOCKCHAIN_SUBMITTED = "BLOCKCHAIN_SUBMITTED", "Blockchain Transaction Submitted"
    COMPLETED = "COMPLETED", "Payment Completed"
    EXPIRED = "EXPIRED", "Expired"
    FAILED = "FAILED", "Payment Failed"
    CANCELLED = "CANCELLED", "Cancelled"


class MerchantQRCode(models.Model):
    """
    Represents a single payment QR code generated by a merchant.
    Contains an HMAC-signed canonical payload to prevent tampering.
    Each QR code is a one-time-use payment intent with a nonce.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    merchant = models.ForeignKey(
        Merchant,
        on_delete=models.PROTECT,
        related_name="qr_codes",
    )

    # Payment parameters embedded in QR
    merchant_wallet_address = models.CharField(max_length=42)
    amount_usdc = models.DecimalField(max_digits=24, decimal_places=8)
    currency = models.CharField(max_length=10, default="USDC")
    description = models.CharField(max_length=255, blank=True)

    # Security: one-time nonce prevents QR replay attacks
    nonce = models.CharField(max_length=64, unique=True, db_index=True)

    # HMAC-SHA256 signature of the canonical payload
    # Verified on scan: prevents payload tampering
    signed_payload = models.TextField()
    hmac_signature = models.CharField(max_length=64)

    # Lifecycle
    status = models.CharField(
        max_length=30,
        choices=QRCodeStatus.choices,
        default=QRCodeStatus.ACTIVE,
        db_index=True,
    )
    expires_at = models.DateTimeField(db_index=True)
    is_consumed = models.BooleanField(default=False, help_text="Permanently lock the QR after successful settlement.")

    # Who scanned/paid (filled on interaction)
    created_for_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="scanned_qr_codes",
    )

    # Linked blockchain transaction (set when tx submitted)
    blockchain_tx_hash = models.CharField(max_length=66, blank=True, db_index=True)

    # Metadata
    scan_count = models.IntegerField(default=0)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "merchant_qr_codes"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["merchant", "status", "-created_at"]),
            models.Index(fields=["expires_at", "status"]),
        ]

    def __str__(self):
        return f"QR {self.nonce[:8]}... {self.amount_usdc} USDC [{self.status}]"

    @property
    def is_active(self) -> bool:
        return self.status == QRCodeStatus.ACTIVE and timezone.now() < self.expires_at

    @property
    def is_expired(self) -> bool:
        return timezone.now() >= self.expires_at

    def build_canonical_payload(self) -> str:
        """Build the deterministic canonical string used for HMAC signing"""
        return json.dumps({
            "merchant_id": str(self.merchant_id),
            "merchant_wallet": self.merchant_wallet_address.lower(),
            "amount_usdc": str(self.amount_usdc),
            "currency": self.currency,
            "nonce": self.nonce,
            "expires_at": self.expires_at.isoformat(),
        }, sort_keys=True)

    def verify_signature(self) -> bool:
        """Verify HMAC signature — called on QR scan"""
        secret = settings.QR_HMAC_SECRET.encode()
        payload = self.build_canonical_payload().encode()
        expected = hmac.new(secret, payload, hashlib.sha256).hexdigest()
        return hmac.compare_digest(self.hmac_signature, expected)

    def transition_to(self, new_status: str) -> bool:
        """Validate and apply status transition"""
        valid_transitions = {
            QRCodeStatus.ACTIVE: [QRCodeStatus.SCANNED, QRCodeStatus.EXPIRED, QRCodeStatus.CANCELLED],
            QRCodeStatus.SCANNED: [QRCodeStatus.PENDING_SIGNATURE, QRCodeStatus.EXPIRED, QRCodeStatus.FAILED],
            QRCodeStatus.PENDING_SIGNATURE: [QRCodeStatus.SIGNATURE_RECEIVED, QRCodeStatus.FAILED],
            QRCodeStatus.SIGNATURE_RECEIVED: [QRCodeStatus.BLOCKCHAIN_SUBMITTED, QRCodeStatus.FAILED],
            QRCodeStatus.BLOCKCHAIN_SUBMITTED: [QRCodeStatus.COMPLETED, QRCodeStatus.FAILED],
        }
        allowed = valid_transitions.get(self.status, [])
        if new_status not in allowed:
            raise ValueError(
                f"Invalid QR transition: {self.status} → {new_status}. "
                f"Allowed: {[s for s in allowed]}"
            )
        self.status = new_status
        self.save(update_fields=["status", "updated_at"])
        return True
